# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(853, 700)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("logo.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(0, 0, 131, 31))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(6)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(260, 0, 141, 31))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(6)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(130, 0, 131, 31))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(6)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(400, 0, 151, 31))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(6)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(550, 0, 151, 31))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(6)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(700, 0, 151, 31))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(6)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setObjectName("pushButton_6")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(80, 60, 170, 41))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(8)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(630, 60, 161, 31))
        self.pushButton_7.setObjectName("pushButton_7")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(240, 60, 361, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(80, 140, 170, 41))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(8)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(240, 140, 361, 31))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(80, 210, 170, 41))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(8)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(240, 210, 361, 31))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(60, 265, 170, 41))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(8)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_4.setGeometry(QtCore.QRect(240, 270, 361, 31))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.pushButton_8 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_8.setGeometry(QtCore.QRect(630, 270, 161, 31))
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_10 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_10.setGeometry(QtCore.QRect(290, 360, 271, 31))
        self.pushButton_10.setObjectName("pushButton_10")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(280, 400, 91, 21))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(190, 430, 221, 181))
        self.label_7.setAutoFillBackground(True)
        self.label_7.setFrameShape(QtWidgets.QFrame.Box)
        self.label_7.setLineWidth(1)
        self.label_7.setText("")
        self.label_7.setWordWrap(False)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(540, 400, 91, 21))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(460, 430, 221, 181))
        self.label_9.setAutoFillBackground(True)
        self.label_9.setFrameShape(QtWidgets.QFrame.Box)
        self.label_9.setLineWidth(1)
        self.label_9.setText("")
        self.label_9.setWordWrap(False)
        self.label_9.setObjectName("label_9")
        self.pushButton_11 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_11.setGeometry(QtCore.QRect(630, 140, 161, 31))
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_9 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_9.setGeometry(QtCore.QRect(290, 360, 271, 31))
        self.pushButton_9.setObjectName("pushButton_9")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(95, 320, 170, 41))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(8)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_6.setGeometry(QtCore.QRect(240, 320, 361, 31))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.pushButton_12 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_12.setGeometry(QtCore.QRect(290, 360, 271, 31))
        self.pushButton_12.setObjectName("pushButton_12")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(240, 110, 351, 71))
        self.textEdit.setObjectName("textEdit")
        self.pushButton_13 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_13.setGeometry(QtCore.QRect(290, 360, 271, 31))
        self.pushButton_13.setObjectName("pushButton_13")
        self.textEdit_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_2.setGeometry(QtCore.QRect(460, 430, 221, 181))
        self.textEdit_2.setObjectName("textEdit_2")
        self.textEdit_3 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_3.setGeometry(QtCore.QRect(240, 210, 351, 81))
        self.textEdit_3.setObjectName("textEdit_3")
        self.pushButton_14 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_14.setGeometry(QtCore.QRect(290, 360, 271, 31))
        self.pushButton_14.setObjectName("pushButton_14")
        self.pushButton_15 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_15.setGeometry(QtCore.QRect(290, 360, 271, 31))
        self.pushButton_15.setObjectName("pushButton_15")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(410, 390, 54, 12))
        self.label_10.setObjectName("label_10")
        self.textEdit_4 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_4.setGeometry(QtCore.QRect(340, 420, 201, 181))
        self.textEdit_4.setObjectName("textEdit_4")

        self.label_5.hide()
        self.label_10.hide()
        self.textEdit.hide()
        self.textEdit_2.hide()
        self.textEdit_3.hide()
        self.textEdit_4.hide()
        self.lineEdit_6.hide()
        self.pushButton_9.hide()
        self.pushButton_12.hide()
        self.pushButton_13.hide()
        self.pushButton_14.hide()
        self.pushButton_15.hide()

        self.pushButton.clicked.connect(self.clickHideImageButton)
        self.pushButton_2.clicked.connect(self.clickHideInfoButton)
        self.pushButton_3.clicked.connect(self.clickExtractImageButton)
        self.pushButton_4.clicked.connect(self.clickExtractInfoButton)
        self.pushButton_5.clicked.connect(self.clickHideTextButton)
        self.pushButton_6.clicked.connect(self.clickExtractTextButton)
        self.pushButton_7.clicked.connect(self.uploadimage1)
        self.pushButton_8.clicked.connect(self.uploadfile1)
        self.pushButton_11.clicked.connect(self.uploadimage2)

        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "InfoHider"))
        self.pushButton.setText(_translate("MainWindow", "图像中隐藏图像"))
        self.pushButton_2.setText(_translate("MainWindow", "图像中隐藏文字"))
        self.pushButton_3.setText(_translate("MainWindow", "图像中提取图像"))
        self.pushButton_4.setText(_translate("MainWindow", "图像中提取文字"))
        self.pushButton_5.setText(_translate("MainWindow", "文字中隐藏文字"))
        self.pushButton_6.setText(_translate("MainWindow", "文字中提取文字"))
        self.label.setText(_translate("MainWindow", "请选择载体图片"))
        self.pushButton_7.setText(_translate("MainWindow", "选择图片"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "请输入载体图片路径"))
        self.label_2.setText(_translate("MainWindow", "需要隐藏的图像"))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindow", "请输入需要隐藏的图像路径"))
        self.label_3.setText(_translate("MainWindow", "输出图片的名称"))
        self.label_4.setText(_translate("MainWindow", "隐写图片输出路径"))
        self.pushButton_8.setText(_translate("MainWindow", "选择输出路径"))
        self.pushButton_10.setText(_translate("MainWindow", "进行图片隐藏"))
        self.label_6.setText(_translate("MainWindow", "载体图像"))
        self.label_8.setText(_translate("MainWindow", "载密图像"))
        self.pushButton_11.setText(_translate("MainWindow", "选择图片"))
        self.pushButton_9.setText(_translate("MainWindow", "进行图片提取"))
        self.label_5.setText(_translate("MainWindow", "请输入6位密钥"))
        self.pushButton_12.setText(_translate("MainWindow", "进行信息隐藏"))
        self.textEdit.setPlaceholderText(_translate("MainWindow", "需要隐藏的信息"))
        self.pushButton_13.setText(_translate("MainWindow", "进行信息提取"))
        self.textEdit_3.setPlaceholderText(_translate("MainWindow", "请输入载体文字"))
        self.pushButton_14.setText(_translate("MainWindow", "进行文字隐藏"))
        self.pushButton_15.setText(_translate("MainWindow", "进行文字提取"))
        self.label_10.setText(_translate("MainWindow", "载密文字"))

        #显示图像中隐藏图像的按钮
    def clickHideImageButton(self,MainWindow):
        self.label.show()
        self.label_2.show()
        self.label_3.show()
        self.label_4.show()
        self.label_6.show()
        self.label_7.show()
        self.label_8.show()
        self.label_9.show()
        self.lineEdit.show()
        self.lineEdit_2.show()
        self.lineEdit_3.show()
        self.lineEdit_4.show()
        self.pushButton_7.show()
        self.pushButton_8.show()
        self.pushButton_10.show()
        self.pushButton_11.show()
        self.label_5.hide()
        self.label_10.hide()
        self.textEdit.hide()
        self.textEdit_2.hide()
        self.textEdit_3.hide()
        self.textEdit_4.hide()
        self.lineEdit_6.hide()
        self.pushButton_9.hide()
        self.pushButton_12.hide()
        self.pushButton_13.hide()
        self.pushButton_14.hide()
        self.pushButton_15.hide()

        self.label_7.clear()
        self.label_9.clear()
        self.lineEdit.clear()
        self.lineEdit_2.clear()
        self.lineEdit_3.clear()
        self.lineEdit_4.clear()

        _translate = QtCore.QCoreApplication.translate
        self.label.setGeometry(QtCore.QRect(80, 60, 170, 41))
        self.label.setText(_translate("MainWindow", "请选择载体图片"))
        self.pushButton_7.setGeometry(QtCore.QRect(630, 60, 161, 31))
        self.pushButton_7.setText(_translate("MainWindow", "选择图片"))
        self.lineEdit.setGeometry(QtCore.QRect(240, 60, 361, 31))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "请输入载体图片路径"))
        self.label_2.setText(_translate("MainWindow", "需要隐藏的图像"))
        self.label_2.setGeometry(QtCore.QRect(80, 140, 170, 41))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindow", "请输入需要隐藏的图像路径"))
        self.label_3.setText(_translate("MainWindow", "输出图片的名称"))
        self.label_3.setGeometry(QtCore.QRect(80, 210, 170, 41))
        self.label_4.setText(_translate("MainWindow", "隐写图片输出路径"))
        self.label_4.setGeometry(QtCore.QRect(60, 265, 170, 41))
        self.pushButton_8.setText(_translate("MainWindow", "选择输出路径"))
        self.pushButton_10.setText(_translate("MainWindow", "进行图片隐藏"))
        self.label_6.setText(_translate("MainWindow", "载体图像"))
        self.label_8.setText(_translate("MainWindow", "载密图像"))
        self.pushButton_11.setText(_translate("MainWindow", "选择图片"))

    #显示提取图像中隐藏的图像的按钮
    def clickExtractImageButton(self, MainWindow):
        self.label.show()
        self.label_3.show()
        self.label_4.show()
        self.label_6.show()
        self.label_7.show()
        self.label_8.show()
        self.label_9.show()
        self.lineEdit.show()
        self.lineEdit_3.show()
        self.lineEdit_4.show()
        self.pushButton_7.show()
        self.pushButton_8.show()
        self.pushButton_9.show()
        self.label_2.hide()
        self.label_5.hide()
        self.label_10.hide()
        self.lineEdit_2.hide()
        self.textEdit.hide()
        self.textEdit_2.hide()
        self.textEdit_3.hide()
        self.textEdit_4.hide()
        self.lineEdit_6.hide()
        self.pushButton_10.hide()
        self.pushButton_11.hide()
        self.pushButton_12.hide()
        self.pushButton_13.hide()
        self.pushButton_14.hide()
        self.pushButton_15.hide()

        self.label_7.clear()
        self.label_9.clear()
        self.lineEdit.clear()
        self.lineEdit_3.clear()
        self.lineEdit_4.clear()

        _translate = QtCore.QCoreApplication.translate
        self.label.setGeometry(QtCore.QRect(80, 140, 170, 41))
        self.label.setText(_translate("MainWindow", "请选择含密图片"))
        self.label_4.setText(_translate("MainWindow", "秘密图片输出路径"))
        self.label_6.setText(_translate("MainWindow", "载密图像"))
        self.label_8.setText(_translate("MainWindow", "秘密图像"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "请输入含密图片路径"))
        self.lineEdit.setGeometry(QtCore.QRect(240, 140, 361, 31))
        self.pushButton_7.setGeometry(QtCore.QRect(630, 140, 161, 31))
        self.pushButton_9.setText(_translate("MainWindow", "进行图片提取"))

    #显示图像中隐藏文字的按钮
    def clickHideInfoButton(self,MainWindow):
        self.label.show()
        self.label_2.show()
        self.label_3.show()
        self.label_4.show()
        self.label_5.show()
        self.label_6.show()
        self.label_7.show()
        self.label_8.show()
        self.label_9.show()
        self.lineEdit.show()
        self.lineEdit_3.show()
        self.lineEdit_4.show()
        self.textEdit.show()
        self.lineEdit_6.show()
        self.pushButton_7.show()
        self.pushButton_8.show()
        self.pushButton_12.show()

        self.label_10.hide()
        self.lineEdit_2.hide()
        self.textEdit_2.hide()
        self.textEdit_3.hide()
        self.textEdit_4.hide()
        self.pushButton_9.hide()
        self.pushButton_10.hide()
        self.pushButton_11.hide()
        self.pushButton_13.hide()
        self.pushButton_14.hide()
        self.pushButton_15.hide()

        self.label_7.clear()
        self.label_9.clear()
        self.lineEdit.clear()
        self.lineEdit_3.clear()
        self.lineEdit_4.clear()
        self.lineEdit_6.clear()
        self.textEdit.clear()

        _translate = QtCore.QCoreApplication.translate
        self.lineEdit.setGeometry(QtCore.QRect(240, 60, 361, 31))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "请输入载体图片路径"))
        self.lineEdit_6.setGeometry(QtCore.QRect(240, 320, 361, 31))
        self.textEdit.setPlaceholderText(_translate("MainWindow", "需要隐藏的信息"))
        self.label.setGeometry(QtCore.QRect(80, 60, 170, 41))
        self.label.setText(_translate("MainWindow", "请选择载体图片"))
        self.label_2.setText(_translate("MainWindow", "需要隐藏的信息"))
        self.label_3.setText(_translate("MainWindow", "输出图片的名称"))
        self.label_5.setText(_translate("MainWindow", "请输入6位密钥"))
        self.label_5.setGeometry(QtCore.QRect(95, 310, 170, 41))
        self.label_6.setText(_translate("MainWindow", "载体图像"))
        self.label_8.setText(_translate("MainWindow", "载密图像"))
        self.pushButton_7.setGeometry(QtCore.QRect(630, 60, 161, 31))

    #显示图像中提取文字的按钮
    def clickExtractInfoButton(self, MainWindow):
        self.label.show()
        self.label_5.show()
        self.label_6.show()
        self.label_7.show()
        self.label_8.show()
        self.lineEdit.show()
        self.lineEdit_6.show()
        self.textEdit_2.show()
        self.pushButton_7.show()
        self.pushButton_13.show()

        self.label_2.hide()
        self.label_3.hide()
        self.label_4.hide()
        self.label_9.hide()
        self.label_10.hide()
        self.lineEdit_2.hide()
        self.lineEdit_3.hide()
        self.lineEdit_4.hide()
        self.textEdit.hide()
        self.textEdit_3.hide()
        self.textEdit_4.hide()
        self.pushButton_8.hide()
        self.pushButton_9.hide()
        self.pushButton_10.hide()
        self.pushButton_11.hide()
        self.pushButton_12.hide()
        self.pushButton_14.hide()
        self.pushButton_15.hide()

        self.label_7.clear()
        self.lineEdit.clear()
        self.lineEdit_6.clear()
        self.textEdit_2.clear()

        _translate = QtCore.QCoreApplication.translate
        self.label.setGeometry(QtCore.QRect(80, 210, 170, 41))
        self.label.setText(_translate("MainWindow", "请输入含密图像"))
        self.label_5.setText(_translate("MainWindow", "请输入6位密钥"))
        self.label_5.setGeometry(QtCore.QRect(95, 300, 170, 41))
        self.lineEdit.setGeometry(QtCore.QRect(240, 210, 361, 31))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "请输入含密图像的路径"))
        self.lineEdit_6.setGeometry(QtCore.QRect(240, 310, 361, 31))
        self.label_6.setText(_translate("MainWindow", "载密图像"))
        self.label_8.setText(_translate("MainWindow", "秘密信息"))
        self.pushButton_7.setGeometry(QtCore.QRect(630, 210, 161, 31))

    #显示文字中隐藏文字的按钮
    def clickHideTextButton(self, MainWindow):
        self.label_2.show()
        self.label_3.show()
        self.label_5.show()
        self.label_10.show()
        self.lineEdit_6.show()
        self.textEdit.show()
        self.textEdit_3.show()
        self.textEdit_4.show()
        self.pushButton_14.show()

        self.label.hide()
        self.label_4.hide()
        self.label_6.hide()
        self.label_7.hide()
        self.label_8.hide()
        self.label_9.hide()
        self.lineEdit.hide()
        self.lineEdit_2.hide()
        self.lineEdit_3.hide()
        self.lineEdit_4.hide()
        self.textEdit_2.hide()
        self.pushButton_7.hide()
        self.pushButton_8.hide()
        self.pushButton_9.hide()
        self.pushButton_10.hide()
        self.pushButton_11.hide()
        self.pushButton_12.hide()
        self.pushButton_13.hide()
        self.pushButton_15.hide()

        self.textEdit.clear()
        self.textEdit_3.clear()
        self.textEdit_4.clear()
        self.lineEdit_6.clear()

        _translate = QtCore.QCoreApplication.translate
        self.label_2.setText(_translate("MainWindow", "请输入秘密文字"))
        self.label_3.setText(_translate("MainWindow", "请输入载体文字"))
        self.label_5.setText(_translate("MainWindow", "请输入密钥"))
        self.label_5.setGeometry(QtCore.QRect(95, 310, 170, 41))
        self.label_10.setGeometry(QtCore.QRect(400, 400, 100, 30))
        self.label_10.setText(_translate("MainWindow", "载密文字"))
        self.textEdit.setPlaceholderText(_translate("MainWindow", "需要隐藏的信息"))
        self.textEdit_4.setGeometry(QtCore.QRect(340, 430, 201, 181))

    #显示文字中提取文字的按钮
    def clickExtractTextButton(self, MainWindow):
        self.label_2.show()
        self.label_3.show()
        self.label_5.show()
        self.label_10.show()
        self.lineEdit_6.show()
        self.textEdit.show()
        self.textEdit_3.show()
        self.textEdit_4.show()
        self.pushButton_15.show()

        self.label.hide()
        self.label_4.hide()
        self.label_6.hide()
        self.label_7.hide()
        self.label_8.hide()
        self.label_9.hide()
        self.lineEdit.hide()
        self.lineEdit_2.hide()
        self.lineEdit_3.hide()
        self.lineEdit_4.hide()
        self.textEdit_2.hide()
        self.pushButton_7.hide()
        self.pushButton_8.hide()
        self.pushButton_9.hide()
        self.pushButton_10.hide()
        self.pushButton_11.hide()
        self.pushButton_12.hide()
        self.pushButton_13.hide()
        self.pushButton_14.hide()

        self.lineEdit_6.clear()
        self.textEdit.clear()
        self.textEdit_3.clear()
        self.textEdit_4.clear()

        _translate = QtCore.QCoreApplication.translate
        self.label_2.setText(_translate("MainWindow", "请输入载密文字"))
        self.label_3.setText(_translate("MainWindow", "请输入载体文字"))
        self.label_5.setText(_translate("MainWindow", "请输入密钥"))
        self.label_5.setGeometry(QtCore.QRect(95, 310, 170, 41))
        self.label_10.setText(_translate("MainWindow", "秘密文字"))
        self.textEdit.setPlaceholderText(_translate("MainWindow", "需要提取的载密文字"))

        #隐藏图像界面选择输出路径按钮
    def uploadfile1(self, Filepath):
        d = QtWidgets.QFileDialog.getExistingDirectory(None, "选取文件夹", "./")  # 起始路径
        name = self.lineEdit_3.text()
        if name.endswith('.jpg') or name.endswith('.png'):
            name = name[:-4]
        else:
            name = name
        if name == '':
            QMessageBox().warning(None, "警告", "请先补全输出图片名称！", QMessageBox.Close)
        else:
            d += '/'
            d += name
            d += '.png'
            self.lineEdit_4.setText(d)

    #隐藏图像界面显示载体图像
    def uploadimage1(self, Filepath):
        a, _ = QtWidgets.QFileDialog.getOpenFileName(None, "选取文件", "./", "*.png;;*.jpg;;*.jpeg")
        self.lineEdit.setText(a)
        jpg = QtGui.QPixmap(a).scaled(self.label_7.width(), self.label_7.height())
        self.label_7.setPixmap(jpg)

    #隐藏图像界面获取私密图像
    def uploadimage2(self, Filepath):
        b, _ = QtWidgets.QFileDialog.getOpenFileName(None, "选取文件", "./", "*.jpg;;*.jpeg;;*.png")
        self.lineEdit_2.setText(b)

    #隐藏图像后显示载密图像
    def showimage1(self):
        imagename = self.lineEdit_4.text()
        jpg = QtGui.QPixmap(imagename).scaled(self.label_9.width(), self.label_9.height())
        self.label_9.setPixmap(jpg)



    # 警告和提示
    def tip1(self):
        QMessageBox().warning(None, "警告", "请确保信息输入完整！", QMessageBox.Close)

    def tip2(self):
        QMessageBox().information(None, "提示", "成功完成图片隐藏!", QMessageBox.Close)

    def tip3(self):
        QMessageBox().information(None, "提示", "成功完成图片提取！", QMessageBox.Close)

    def tip4(self):
        QMessageBox().warning(None, "警告", "载体图片大小需大于要隐藏的图片！", QMessageBox.Close)

    def success1(self):
        QMessageBox().information(None, "提示", "成功完成文本信息隐藏！", QMessageBox.Close)

    def success2(self):
        QMessageBox().information(None, "提示", "成功完成文本信息提取！", QMessageBox.Close)

    def warn2(self):
        QMessageBox().warning(None, "警告", "输入密钥非6位！", QMessageBox.Close)

    def warn4(self):
        QMessageBox().information(None, "提示", "找不到图片中隐藏信息！", QMessageBox.Close)

    def warn5(self):
        QMessageBox().warning(None, "警告", "输入的密钥不正确！", QMessageBox.Close)

    def warn6(self):
        QMessageBox().warning(None, "警告", "请输入正确的密文、密钥和载体！", QMessageBox.Close)